wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
architecture:
  desc: null
  value: transformer+CNN+FC
dataset:
  desc: null
  value: VizWiz
epochs:
  desc: null
  value: 30
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.17.3
    framework: huggingface
    huggingface_version: 4.42.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1720059357
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.11
      5: 0.17.3
      6: 4.42.3
      8:
      - 3
      - 5
      13: windows-amd64
